import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const [products, setPictures] = useState([
    {
      id: 0,
      sku: "GX6947",
      name: "adidas Adilette Slide Carbon Aluminium",
      size: "38",
      product_url:
        "https://restocks.net/nl/p/adidas-adilette-slides-carbon-aluminium",
      image_url:
        "https://media.restocks.net/products/GX6947/adidas-adilette-slides-carbon-aluminium-1-400.png",
      alt: "adidas-adilette-slides-carbon-aluminium",
    },
    {
      id: 1,
      sku: "DH6927-111",
      name: "Air Jordan 4 Retro Military Black",
      size: "42",
      product_url:
        "https://restocks.net/nl/p/air-jordan-4-retro-military-black",
      image_url:
        "https://media.restocks.net/products/DH6927-111/air-jordan-4-retro-military-black-1-400.png",
      alt: "air-jordan-4-retro-military-black",
    },
    {
      id: 2,
      sku: "DH6927-140",
      name: "Air Jordan 4 Retro White Midnight Navy",
      size: "42,5",
      product_url:
        "https://restocks.net/nl/p/air-jordan-4-retro-white-midnight-navy",
      image_url:
        "https://media.restocks.net/products/DH6927-140/air-jordan-4-retro-white-midnight-navy-1-400.png",
      alt: "air-jordan-4-retro-white-midnight-navy",
    },
    {
      id: 3,
      sku: "553558-615",
      name: "Air Jordan 1 Low Bordeaux",
      size: "41",
      product_url: "https://restocks.net/nl/p/air-jordan-1-low-bordeaux",
      image_url:
        "https://media.restocks.net/products/553558-615/air-jordan-1-low-bordeaux-1-400.png",
      alt: "air-jordan-1-low-bordeaux",
    },
    {
      id: 4,
      sku: "DC0774-114",
      name: "Air Jordan 1 Low Marina Blue (W)",
      size: "36,5",
      product_url: "https://restocks.net/nl/p/air-jordan-1-low-marina-blue-w",
      image_url:
        "https://media.restocks.net/products/DC0774-114/air-jordan-1-low-marina-blue-w-1-400.png",
      alt: "air-jordan-1-low-marina-blue-w",
    },
    {
      id: 5,
      sku: "555088-711",
      name: "Air Jordan 1 Retro High OG Yellow Toe",
      size: "40",
      product_url:
        "https://restocks.net/nl/p/air-jordan-1-retro-high-og-yellow-toe",
      image_url:
        "https://media.restocks.net/products/555088-711/air-jordan-1-retro-high-og-yellow-toe-1-400.png",
      alt: "air-jordan-1-retro-high-og-yellow-toe",
    },
    {
      id: 6,
      sku: "555088-711",
      name: "Air Jordan 1 Retro High OG Yellow Toe",
      size: "40,5",
      product_url:
        "https://restocks.net/nl/p/air-jordan-1-retro-high-og-yellow-toe",
      image_url:
        "https://media.restocks.net/products/555088-711/air-jordan-1-retro-high-og-yellow-toe-1-400.png",
      alt: "air-jordan-1-retro-high-og-yellow-toe",
    },
    {
      id: 7,
      sku: "555088-711",
      name: "Air Jordan 1 Retro High OG Yellow Toe",
      size: "40,5",
      product_url:
        "https://restocks.net/nl/p/air-jordan-1-retro-high-og-yellow-toe",
      image_url:
        "https://media.restocks.net/products/555088-711/air-jordan-1-retro-high-og-yellow-toe-1-400.png",
      alt: "air-jordan-1-retro-high-og-yellow-toe",
    },
    {
      id: 10,
      sku: "555088-711",
      name: "Air Jordan 1 Retro High OG Yellow Toe",
      size: "42,5",
      product_url:
        "https://restocks.net/nl/p/air-jordan-1-retro-high-og-yellow-toe",
      image_url:
        "https://media.restocks.net/products/555088-711/air-jordan-1-retro-high-og-yellow-toe-1-400.png",
      alt: "air-jordan-1-retro-high-og-yellow-toe",
    },
    {
      id: 19,
      sku: "DH7138-006",
      name: "Jordan 4 Retro SE Black Canvas",
      size: "42,5",
      product_url:
        "https://restocks.net/nl/p/air-jordan-4-retro-se-black-canvas",
      image_url:
        "https://media.restocks.net/products/DH7138-006/air-jordan-4-retro-se-black-canvas-1-400.png",
      alt: "air-jordan-4-retro-se-black-canvas",
    },
  ]);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sneaker Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main
        className="font-mandali dark:bg-gray-900 dark:text-white 
        text-center min-h-screen flex flex-col"
      >
        <section className="px-5 md:px-10">
          <nav className="py-10 flex justify-between items-center">
            <h1 className="text-xl md:text-4xl font-[600] mr-12">
              Sneaker Portfolio
            </h1>
            <BsFillMoonStarsFill
              className="cursor-pointer text-lg md:text-2xl "
              onClick={() => setDarkMode((prev) => !prev)}
            />
          </nav>
        </section>
        <section className="flex-1 md:mx-12">
          <div className="w-full flex justify-center flex-wrap">
            {products.map((product) => (
              <div
                key={product.id}
                className="group relative text-xs md:text-sm lg:text-lg cursor-pointer rounded-xl hover:bg-gray-100 hover:shadow-inner hover:delay-75 dark:hover:bg-gray-500  w-1/3 md:w-1/4 lg:w-1/6"
              >
                <a href={product.product_url}>
                  <img
                    src={`https://images.weserv.nl/?url=${product.image_url}?fit=fill&w=300&h=214&fm=webp&auto=compress&trim=color&q=90&dpr=2`}
                    alt={`${product.alt}`}
                  />
                </a>
                <p className="leading-1 md:leading-normal mx-1">
                  {product.name}
                </p>
                <span className="absolute top-1 left-2 font-bold bg-gray-100 group-hover:bg-white dark:group-hover:bg-gray-900 group-hover:delay-75 dark:bg-gray-700 rounded-xl p-1">
                  {product.size}
                </span>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
